Appendix:
    -Slope & Y-intercept (Linear)
    -Solve Linear Function (y=mx+b)
    -Break Even Calculator
    -Correlation Coefficient (Vector)
    -Solving Linear Systems Calculator
    -Matrix Inverse Calculator (+ identity and solve) 

# Slope and Y-intercept (linear)

In [98]:
def getSlope(x1, y1, x2, y2):
    slope = (y2-y1)/(x2-x1)
    return slope

def getYInt(x1, y1, x2, y2):
    m=getSlope(x1,y1,x2,y2)
    b=y1-m*x1
    return print((0,b))

In [99]:
#Input for slope here:
getSlope(0, 0, 7, 215)

30.714285714285715

In [101]:
#Input for Y-intercept here:
getYInt(0, 0, 7, 215)
#(0,b)

(0, 0.0)


# Solve Linear Function (y=mx+b)

In [30]:
from math import *
m = float(input("Enter Slope): "))
x = float(input("Enter x of f(x): "))
b = float(input("Enter Y-intercept: "))

Enter Slope): 1.24
Enter x of f(x): 340
Enter Y-intercept: 400


In [35]:
y=m*x+b
print (y)
#ordered pair
print ((x,y))

821.6
(340.0, 821.6)


Reverse Operation:
Finding x value from f(x).

In [36]:
#f(x)=y
y = float(input("Enter f(x) value:"))
m = float(input("Enter Slope): "))
b = float(input("Enter Y-intercept: "))

Enter f(x) value:1416.8
Enter Slope): 1.24
Enter Y-intercept: 400


In [37]:
x=(y-b)/m
print (x)
#ordered pair
print ((x,y))

820.0
(820.0, 1416.8)


# Break Even Calculator

In [81]:
from sympy import Symbol, Derivative, integrate
import math

In [87]:
#Calculate C(x), R(x), P(x) (Cost Function)
b = float(input("Enter fixed cost: "))
m = float(input("Enter variable cost: "))
R = float(input("Enter revenue (price): "))
x = Symbol('x')

Enter fixed cost: 530
Enter variable cost: 2.3
Enter revenue (price): 4.90


In [88]:
#C(x) Cost Function
print (f"{m}*{x}+{b}")
#R(x) Revenue Function
print (R*x)
#P(x) Profit Function
p = R-m
print (f"{p}*x+{b}")
print (p*x-b)

2.3*x+530.0
4.9*x
2.6000000000000005*x+530.0
2.6*x - 530.0


In [89]:
break_even = b/p

print (break_even)

203.8461538461538


In [90]:
#Enter Profit
pfunc = 2000
number =(pfunc+b)/p
print(number)


973.0769230769229


# Correlation Coefficient (from vectors)

In [110]:
from scipy import stats
x = [0, 1, 2, 3, 4, 5, 6, 7]
y = [0, 44, 86, 111, 120, 150, 202, 216]
slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)

#Below is for prediction given 'x'
predict_2020 = 11 * slope + intercept

print("slope = ", round(slope, 3))
print("intercept = ", round(intercept, 2))
print("The death rate in 2020 will be approximately", round(predict_2020, 2), "per 100,000 population.")
print("correlation coefficient = ", round(r_value, 4))

slope =  29.798
intercept =  11.83
The death rate in 2020 will be approximately 339.61 per 100,000 population.
correlation coefficient =  0.9889


# Solving Linear Systems Calculator

Example:

4x+3y-5z=2
-2x-4y+5=5
8x+8y=-3

Note: fill in zero "0" for missing values

A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

In [111]:
import numpy as np

A = np.array([[1, 1, 1], 
              [15, 20, 25], 
              [11, 18, 34]])
y = np.array([210, 4450, 4985])

x = np.linalg.solve(A, y)
print(x)

[45. 70. 95.]


# Matrix Inverses

In [114]:
import numpy as np
from numpy.linalg import linalg, inv

In [117]:
#Below is for values of matrix.
rhs = [96, 87, 74]
rhs = np.matrix(rhs)
rhs = np.transpose(rhs)
print('\nRight Hand Side of Equation')
print(rhs)

#Below is for matrix
A = [[1, 2, 0], [-2, -3, 5], [0, 0, 1]]
A = np.matrix(A)
print('\nMatrix A')
print(A)


Right Hand Side of Equation
[[96]
 [87]
 [74]]

Matrix A
[[ 1  2  0]
 [-2 -3  5]
 [ 0  0  1]]


In [118]:
#Find Inverse of Matrix a here:
print('\nInverse of A')
IA = inv(A)
print(IA)


Inverse of A
[[-3. -2. 10.]
 [ 2.  1. -5.]
 [ 0.  0.  1.]]


In [ ]:
#identity Matrix
print('\nIdentity Matrix')
I = np.dot(IA, A)
I = np.rint(I)               # This converts floating point to integer.
print(I)

In [ ]:
#Solve Matrix
print('\Illustration of solution with linalg.solve(,) function')
result2 = linalg.solve(A, rhs)
print(np.rint(result2))    # This converts floating point to integer.

In [ ]:
#Solve matrix (option 2)
result = np.dot(IA, rhs)
result = np.rint(result)    # This converts floating point to integer.
print('\n Solution to Problem')
print(result)