Appendix:
    -Slope & Y-intercept (Linear)
    -Solve Linear Function (y=mx+b)
    -Break Even Calculator
    -Correlation Coefficient (Vector)
    -Solving Linear Systems Calculator
    -Matrix Inverse Calculator (+ identity and solve) 

# Slope and Y-intercept (linear)

In [98]:
def getSlope(x1, y1, x2, y2):
    slope = (y2-y1)/(x2-x1)
    return slope

def getYInt(x1, y1, x2, y2):
    m=getSlope(x1,y1,x2,y2)
    b=y1-m*x1
    return print((0,b))

In [99]:
#Input for slope here:
getSlope(0, 0, 7, 215)

30.714285714285715

In [101]:
#Input for Y-intercept here:
getYInt(0, 0, 7, 215)
#(0,b)

(0, 0.0)


# Solve Linear Function (y=mx+b)

In [30]:
from math import *
m = float(input("Enter Slope): "))
x = float(input("Enter x of f(x): "))
b = float(input("Enter Y-intercept: "))

Enter Slope): 1.24
Enter x of f(x): 340
Enter Y-intercept: 400


In [35]:
y=m*x+b
print (y)
#ordered pair
print ((x,y))

821.6
(340.0, 821.6)


Reverse Operation:
Finding x value from f(x).

In [36]:
#f(x)=y
y = float(input("Enter f(x) value:"))
m = float(input("Enter Slope): "))
b = float(input("Enter Y-intercept: "))

Enter f(x) value:1416.8
Enter Slope): 1.24
Enter Y-intercept: 400


In [37]:
x=(y-b)/m
print (x)
#ordered pair
print ((x,y))

820.0
(820.0, 1416.8)


# Break Even Calculator

In [116]:
from sympy import Symbol, Derivative, integrate
import math

In [117]:
#Calculate C(x), R(x), P(x) (Cost Function)
b = float(input("Enter fixed cost: "))
m = float(input("Enter variable cost: "))
R = float(input("Enter revenue (price): "))
x = Symbol('x')

Enter fixed cost: 280
Enter variable cost: 5
Enter revenue (price): 19


In [118]:
#C(x) Cost Function
print (f"{m}*{x}+{b}")
#R(x) Revenue Function
print (R*x)
#P(x) Profit Function
p = R-m
print (p*x-b)

5.0*x+280.0
19.0*x
14.0*x - 280.0


In [119]:
break_even = b/p

print (break_even)

20.0


In [90]:
#Enter Profit
pfunc = 2000
number =(pfunc+b)/p
print(number)


973.0769230769229


# Correlation Coefficient (from vectors)

In [128]:
from scipy import stats
x = [157, 250, 340, 350, 391, 191, 219]
y = [32.8, 27.7, 13.1, 17, 10.2, 35.8, 42.2]
slope, intercept, r_value, p_value, std_err = stats.linregress(x, y)

#Below is for prediction given 'x'
predict_2020 = 30 * slope + intercept

print("slope = ", round(slope, 4))
print("intercept = ", round(intercept, 4))
print("The death rate in 2020 will be approximately", round(predict_2020, 2), "per 100,000 population.")
print("correlation coefficient = ", round(r_value, 4))

slope =  -0.1238
intercept =  59.1025
The death rate in 2020 will be approximately 55.39 per 100,000 population.
correlation coefficient =  -0.9018


# Solving Linear Systems Calculator

Example:

4x+3y-5z=2
-2x-4y+5=5
8x+8y=-3

Note: fill in zero "0" for missing values

A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

In [129]:
import numpy as np

A = np.array([[1, 1, 1], 
              [0, 1, -1], 
              [.04, .05, .06]])
y = np.array([50500, 2500, 2435])

x = np.linalg.solve(A, y)
print(x)

[22000. 15500. 13000.]


In [123]:
import numpy as np

A = np.array([[1, 1], 
              [20, 30]])
y = np.array([231, 4700])

x = np.linalg.solve(A, y)
print(x)

[223.   8.]


# Matrix Inverses

In [114]:
import numpy as np
from numpy.linalg import linalg, inv

In [117]:
Example:
    
#Below is for values of matrix.
rhs = [96, 87, 74]
rhs = np.matrix(rhs)
rhs = np.transpose(rhs)
print('\nRight Hand Side of Equation')
print(rhs)

#Below is for matrix
A = [[1, 2, 0], [-2, -3, 5], [0, 0, 1]]
A = np.matrix(A)
print('\nMatrix A')
print(A)


Right Hand Side of Equation
[[96]
 [87]
 [74]]

Matrix A
[[ 1  2  0]
 [-2 -3  5]
 [ 0  0  1]]


In [7]:
#Below is for values of matrix.
rhs = [-1, 2]
rhs = np.matrix(rhs)
rhs = np.transpose(rhs)
print('\nRight Hand Side of Equation')
print(rhs)


Right Hand Side of Equation
[[-1]
 [ 2]]


In [8]:
#Below is for matrix
A = [[7, -25],[-1, 5]]
A = np.matrix(A)
print('\nMatrix A')
print(A)


Matrix A
[[  7 -25]
 [ -1   5]]


In [9]:
#Find Inverse of Matrix a here:
print('\nInverse of A')
IA = inv(A)
print(IA)


Inverse of A
[[0.5 2.5]
 [0.1 0.7]]


Note that the function np.dot() performs matrix multiplication. Verify inverse by multiplying matrix A and its inverse IA.

The code below can also be used for Matrix Multipications.

In [10]:
#identity Matrix
print('\nIdentity Matrix')
I = np.dot(IA, A)
I = np.rint(I)               # This converts floating point to integer.
print(I)


Identity Matrix
[[1. 0.]
 [0. 1.]]


In [12]:
#Solve Matrix
print('\Illustration of solution with linalg.solve(,) function')
result2 = linalg.solve(A, rhs)
print(np.rint(result2)) # This converts floating point to integer.
print(result2) #Kept as float

\Illustration of solution with linalg.solve(,) function
[[4.]
 [1.]]
[[4.5]
 [1.3]]


In [ ]:
#Solve matrix (option 2)
result = np.dot(IA, rhs)
result = np.rint(result)    # This converts floating point to integer.
print('\n Solution to Problem')
print(result)

# Matrix Multipications

In [1]:
import numpy as np
from numpy.linalg import linalg, inv

In [2]:
#Below is for matrix #1
A = [[13000, 11000], [22000, 23000], [28000, 35000], [64000, 56000]]
A = np.matrix(A)
print('\nMatrix A')
print(A)


Matrix A
[[13000 11000]
 [22000 23000]
 [28000 35000]
 [64000 56000]]


In [3]:
#Below is for matrix #2
B = [[.12, 0, 0, 0], [0, .08, 0, 0], [0, 0, 0.07, 0], [0, 0, 0, 0.19]]
B = np.matrix(B)
print('\nMatrix B')
print(B)


Matrix B
[[0.12 0.   0.   0.  ]
 [0.   0.08 0.   0.  ]
 [0.   0.   0.07 0.  ]
 [0.   0.   0.   0.19]]


In [4]:
#identity Matrix
print('\Multiply Matrix')
M = np.dot(B, A)
M = np.rint(M)               # This converts floating point to integer.
print(M)

\Multiply Matrix
[[ 1560.  1320.]
 [ 1760.  1840.]
 [ 1960.  2450.]
 [12160. 10640.]]


# Relative and Absolute Extrema

In [142]:
import numpy as np
import matplotlib.pyplot as plt

In [143]:
#Run and Disregard
def extrema(a, b, c):
    x = max(a, b, c)
    z = min(a, b, c)
    epsilon = 0.0000001  # This is a safeguard against minor differences.
    result = False
    if abs(b - x) < epsilon:
        result = True
    if abs(b - z) < epsilon:
        result = True
    return result

In [144]:
##Enter Function Below:
def f(x):
    y = (x**2 + 16)/(4**x)
    return y

In [145]:
##Define End Points:
xa = 1
xb = 12

In [146]:
#Run and Disregard
n = 1000
delta = (xb - xa) / n
x = np.arange(xa, xb + delta, delta)
y = f(x)

value = [False]  # This defines the list value which will contain Boolean values.
value = value * len(x)  # This expands the list to the length of x.

L = len(x)
value[0] = True  # This will correspond to one endpoint.
value[L - 1] = True  # This corresponds to the other.

In [147]:
#Run for Value:
for x_index in range(L - 2):
    first_x = x[x_index]
    second_x = x[x_index + 1]
    third_x = x[x_index + 2]
    a = f(first_x)
    b = f(second_x)
    c = f(third_x)
    is_second_x_extrema = extrema(a, b, c)
    value[x_index + 1] = is_second_x_extrema

for k in range(L - 2):
    value[k + 1] = extrema(f(x[k]), f(x[k + 1]), f(x[k + 2]))

max_value = max(y)  # We check the list to find the global maxima.
min_value = min(y)# We check the list to find the global minima.
print(f"the min y value is: ", min_value)
print(f"the max y value is: ", max_value)

the min y value is:  9.536743164063694e-06
the max y value is:  4.25


# Functions of two variables (x, y)

Example:

f(x, y) = 4x^2 - 9xy +6y^3

Let us find partial derivitives for x and y individually. It is incredibly easy with sympy as we saw last week.

In [138]:
from sympy import symbols

x, y = symbols('x, y')
#Enter Function Here:
f_x_y = 4 * x**2 - 9 * x * y + 6 * y**3

partial_f_x = f_x_y.diff(x)  # Differentiate our equation with respect to x
print(f"Partial Derivitive of our equation with respect to x: {partial_f_x}")

partial_f_y = f_x_y.diff(y)  # Differentiate our equation with respect to y
print(f"Partial Derivitive of our equation with respect to y: {partial_f_y}")

Partial Derivitive of our equation with respect to x: 8*x - 9*y
Partial Derivitive of our equation with respect to y: -9*x + 18*y**2


In [139]:
#We can continue by taking the second derivitive of either. 
partial_y_y = partial_f_y.diff(y) 
partial_y_x = partial_f_y.diff(x)

print(f"Second derivitive fyy(x,y): {partial_y_y}")
print(f"Second derivitive fyx(x,y): {partial_y_x}")

Second derivitive fyy(x,y): 36*y
Second derivitive fyx(x,y): -9


# Finding Extrema (Two Functions (x, y))

In [48]:
#Don't Use this one. Use option 2.
from sympy import symbols, S, linsolve

x, y = symbols('x, y')

#Enter Function Below:
f_x_y = -x**2 - y**2 + 4*x + 8*y
partial_x = f_x_y.diff(x)
partial_y = f_x_y.diff(y)

results = linsolve([partial_x, partial_y], x, y)

print(f"The x and y value for critical points are {results}")


NonlinearError: 

We now want to see if the critical point we've found is a relative maxima, minima, saddle point, or none of them. We do this by calculating the discriminant D. 

In [140]:
from sympy import lambdify, Abs

def D(func, x_sym, y_sym, x_crit, y_crit):
    # Calculate the discriminant for a given function
    f_x_x = func.diff(x_sym, x_sym)
    f_y_y = func.diff(y_sym, y_sym)
    f_x_y = func.diff(x_sym, y_sym)
    
    # Create callable functions for each of the derivitives we created
    lambd_x_x = lambdify([x_sym, y_sym], f_x_x)
    lambd_y_y = lambdify([x_sym, y_sym], f_y_y)
    lambd_x_y = lambdify([x_sym, y_sym], f_x_y)

    fxx_ab = lambd_x_x(x_crit, y_crit)
    fyy_ab = lambd_y_y(x_crit, y_crit) 
    fxy_ab = lambd_x_y(x_crit, y_crit)

    d = fxx_ab * fyy_ab - Abs(fxy_ab)**2

    print(f"The discriminant of our critical value is {d}")

    if d < 0:
        print("This is a saddle point")
    elif d > 0:
        if fxx_ab < 0:
            print("This is relative maxima")
        else:
            print("This is a relative minima")
    

# Call our new function and pass in the values
D(f_x_y, x, y, -2, -1)

The discriminant of our critical value is -369
This is a saddle point


In [148]:
#Option 2 for non-real numbers:
from sympy import symbols, S, nonlinsolve

x, y = symbols('x, y', real=True)

f_x_y = (x**2 + 16)/(4**x)
partial_x = f_x_y.diff(x)
partial_y = f_x_y.diff(y)

# Get nonlinear solution and remove imaginary numbers
results = nonlinsolve([partial_x, partial_y], [x, y])

print(f"The x and y value for critical points are {results}")

for result in list(results):
    if result[0].is_real and result[1].is_real:  # Ignore any solutions that are not real numbers
        print(f"Analyzing critical point {result}")
        D(f_x_y, x, y, result[0], result[1])

The x and y value for critical points are FiniteSet((1/(2*log(2)) - I*sqrt(-1 + 8*log(2))*sqrt(1 + 8*log(2))/(2*log(2)), y), (1/(2*log(2)) + I*sqrt(-1 + 8*log(2))*sqrt(1 + 8*log(2))/(2*log(2)), y))


# Lagrange Multipliers

Suppose we want to maximize the area of a rectangle x/y with the function f(x, y) = x *y

This is constrained however by the function:

g(x, y) = xy + 20y + 20x + 474000 = 500000

We first set our constraint equal to zero, and then solve for x and y.

In [47]:
from sympy import symbols, nonlinsolve, nsimplify, expand, powsimp

x, y, l = symbols('x, y, l', real=True)

f_xy = -x**2 - y**2 + 4*x + 8*y
g_xy = x * y + 20 * y + 20 * x + 474000 - 500000  # Constraint is equal to zero when subtracting right side

# Implement lagrange function and solve system
f_xyl = f_xy - l *g_xy
f_xyl_x = f_xyl.diff(x)
f_xyl_y = f_xyl.diff(y)
f_xyl_l = f_xyl.diff(l)

results = nonlinsolve([
    f_xyl_x,
    f_xyl_y,
    f_xyl_l,
], [x, y, l])

# Analyze each of the solutions
for sol in list(results):
    x_sol, y_sol, l_sol = sol

    x_sol = x_sol.evalf()  # Evaluate the value so we're not getting sqrt equation
    y_sol = y_sol.evalf()
    print(f"Max value of x is {x_sol}")
    print(f"Max value of y is {y_sol}")

    print(f"Max area is of ({x_sol}, {y_sol}) is {x_sol * y_sol}")

Max value of x is 142.480768092719
Max value of y is 142.480768092719
Max area is of (142.480768092719, 142.480768092719) is 20300.7692762912
Max value of x is -182.480768092719
Max value of y is -182.480768092719
Max area is of (-182.480768092719, -182.480768092719) is 33299.2307237088


In [137]:
f_x = (x**2 + 16)/(4**x)
derivative = f_x.diff(x)

AttributeError: 'numpy.ndarray' object has no attribute 'diff'